[build]
  command = ""
  publish = "src"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@notionhq/client", "node-fetch"]

[[redirects]]
  from = "/pages/privacy"
  to = "/pages/privacy.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/terms"
  to = "/pages/terms.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/faq"
  to = "/pages/faq.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/contact"
  to = "/pages/contact.html"
  status = 301
  force = true